-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 00:28:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smartflow
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartflow` ;

-- -----------------------------------------------------
-- Schema smartflow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartflow` DEFAULT CHARACTER SET utf8 ;
USE `smartflow` ;

-- -----------------------------------------------------
-- Table `smartflow`.`channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`channel` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`channel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `device_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_channel_device_idx` (`device_id` ASC),
  CONSTRAINT `fk_channel_device`
    FOREIGN KEY (`device_id`)
    REFERENCES `smartflow`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`classification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`classification` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`classification` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`client` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`client` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `plan_id` INT(11) NOT NULL,
  `disabled` BIT(1) NOT NULL,
  `show_gateway_logo` BIT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_plan_idx` (`plan_id` ASC),
  CONSTRAINT `fk_client_plan`
    FOREIGN KEY (`plan_id`)
    REFERENCES `smartflow`.`plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`device` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`device` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `is_panel` BIT(1) NOT NULL,
  `description` VARCHAR(255) NULL,
  `device_ip` VARCHAR(255) NOT NULL,
  `mac_address` VARCHAR(17) NOT NULL,
  `disabled` BIT(1) NOT NULL,
  `task_id` INT(11) NULL,
  `entry_device` BIT(1) NULL,
  `interval_time_notification` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_device_store_idx` (`store_id` ASC),
  CONSTRAINT `fk_device_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `smartflow`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`modules` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`modules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`plan` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`plan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`plan_has_modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`plan_has_modules` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`plan_has_modules` (
  `plan_id` INT(11) NOT NULL,
  `modules_id` INT(11) NOT NULL,
  INDEX `fk_plano_has_modules_modules1_idx` (`modules_id` ASC),
  INDEX `fk_plano_has_modules_plano_idx` (`plan_id` ASC),
  CONSTRAINT `fk_plano_has_modules_plano`
    FOREIGN KEY (`plan_id`)
    REFERENCES `smartflow`.`plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plano_has_modules_modules1`
    FOREIGN KEY (`modules_id`)
    REFERENCES `smartflow`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`record` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`record` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `count_in` INT NULL,
  `count_out` INT NULL,
  `timestamp` DATETIME NOT NULL,
  `classification_id` INT(11) NOT NULL,
  `channel_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `classification_id`),
  INDEX `fk_record_classification_idx` (`classification_id` ASC),
  INDEX `fk_record_channel_idx` (`channel_id` ASC),
  CONSTRAINT `fk_record_classification`
    FOREIGN KEY (`classification_id`)
    REFERENCES `smartflow`.`classification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_channel`
    FOREIGN KEY (`channel_id`)
    REFERENCES `smartflow`.`channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`role` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`statistics_zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`statistics_zone` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`statistics_zone` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `count` INT NULL,
  `max_fill_level` INT NULL,
  `max_dwell` DOUBLE NULL,
  `mean_dwell` DOUBLE NULL,
  `classification_id` INT(11) NOT NULL,
  `zone_id` INT(11) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `classification_id`),
  INDEX `fk_statistics_zone_classification_idx` (`classification_id` ASC),
  INDEX `fk_statistics_zone_zone_idx` (`zone_id` ASC),
  CONSTRAINT `fk_statistics_zone_classification`
    FOREIGN KEY (`classification_id`)
    REFERENCES `smartflow`.`classification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statistics_zone_zone`
    FOREIGN KEY (`zone_id`)
    REFERENCES `smartflow`.`zone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`store` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`store` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `client_id` INT(11) NOT NULL,
  `email` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `max_allowed` INT NOT NULL,
  `panel_language` VARCHAR(100) NULL,
  `logo_path` VARCHAR(255) NULL,
  `url_path` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  INDEX `fk_store_client_idx` (`client_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_store_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `smartflow`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`tracking_lines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`tracking_lines` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`tracking_lines` (
  `id` INT NOT NULL,
  `exit_time` TIMESTAMP(1) NULL,
  `person_id` INT NULL,
  `entry_x` INT(11) NULL,
  `entry_y` INT(11) NULL,
  `exit_x` INT(11) NULL,
  `exit_y` INT(11) NULL,
  `classification_id` INT(11) NOT NULL,
  `zone_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `zone_id`),
  INDEX `fk_tracking_lines_classification1_idx` (`classification_id` ASC),
  INDEX `fk_tracking_lines_zone1_idx` (`zone_id` ASC),
  CONSTRAINT `fk_tracking_lines_classification1`
    FOREIGN KEY (`classification_id`)
    REFERENCES `smartflow`.`classification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tracking_lines_zone1`
    FOREIGN KEY (`zone_id`)
    REFERENCES `smartflow`.`zone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`user` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `role_id` INT(11) NOT NULL,
  `disabled` BIT(1) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `client_id` INT(11) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `role_id`, `client_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_role_idx` (`role_id` ASC),
  INDEX `fk_user_client_idx` (`client_id` ASC),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `smartflow`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `smartflow`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`user_has_store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`user_has_store` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`user_has_store` (
  `user_id` INT(11) NOT NULL,
  `store_id` INT(11) NOT NULL,
  INDEX `fk_user_has_store_store_idx` (`store_id` ASC),
  INDEX `fk_user_has_store_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_store_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `smartflow`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_store_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `smartflow`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartflow`.`zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartflow`.`zone` ;

CREATE TABLE IF NOT EXISTS `smartflow`.`zone` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `device_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_zone_device_idx` (`device_id` ASC),
  CONSTRAINT `fk_zone_device`
    FOREIGN KEY (`device_id`)
    REFERENCES `smartflow`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
